name: Build BebzOS ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          set -e
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get clean
          sudo apt-get update -o Acquire::Retries=3
          sudo apt-get install -y --no-install-recommends live-build debootstrap || (sudo apt-get -f install -y && sudo apt-get install -y --no-install-recommends live-build debootstrap)
          sudo apt-get check
          dpkg -l

      - name: Run build script
        run: sudo bash build-bebzos.sh

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: bebzos-iso
          path: build/live-image-*.iso